# Generated by Django 6.0 on 2025-12-13 17:26

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=50, unique=True, verbose_name="Name"),
                ),
                (
                    "ticker",
                    models.CharField(max_length=50, unique=True, verbose_name="Ticker"),
                ),
                (
                    "exchange",
                    models.CharField(
                        choices=[("nse", "NSE"), ("bse", "BSE")],
                        max_length=3,
                        verbose_name="Exchange",
                    ),
                ),
                ("sector", models.CharField(max_length=20, verbose_name="Sector")),
                ("industry", models.CharField(max_length=20, verbose_name="Industry")),
                ("listing_date", models.DateField(verbose_name="Listing Date")),
                ("is_active", models.BooleanField(verbose_name="Active?")),
            ],
            options={
                "verbose_name_plural": "Companies",
            },
        ),
        migrations.CreateModel(
            name="Metric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=50, verbose_name="Metric Code")),
                ("name", models.CharField(max_length=50, verbose_name="Name")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("IS", "Income Statement"),
                            ("BS", "Balance Sheet"),
                            ("CF", "Cash Flow"),
                            ("RATIO", "Financial Ratios"),
                        ],
                        max_length=5,
                        verbose_name="Category",
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("INR", "Indian Rupees"),
                            ("CRORE", "Crores"),
                            ("PERCENT", "Percentage"),
                            ("RATIO", "Ratio"),
                            ("COUNT", "Count"),
                        ],
                        max_length=10,
                        verbose_name="Unit",
                    ),
                ),
                ("is_derived", models.BooleanField(verbose_name="is Derived Metric?")),
            ],
            options={
                "verbose_name": "Metric",
                "verbose_name_plural": "Metrices",
            },
        ),
        migrations.CreateModel(
            name="TimePeriod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.SmallIntegerField(verbose_name="Year")),
                ("quarter", models.SmallIntegerField(verbose_name="Quarter")),
                (
                    "period_type",
                    models.CharField(
                        choices=[
                            ("annual", "Annual"),
                            ("quarterly", "Quarterly"),
                            ("ttm", "Trailing Twelve Months"),
                        ],
                        max_length=10,
                        verbose_name="Period Type",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="Start Date")),
                ("end_date", models.DateField(verbose_name="End Date")),
                (
                    "is_complete",
                    models.BooleanField(default=True, verbose_name="Is Complete?"),
                ),
            ],
            options={
                "verbose_name": "Time Period",
                "verbose_name_plural": "Time Periods",
            },
        ),
    ]
