# Generated by Django 6.0 on 2025-12-13 19:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stocks", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="company",
            options={"verbose_name": "Company", "verbose_name_plural": "Companies"},
        ),
        migrations.AlterField(
            model_name="metric",
            name="code",
            field=models.CharField(
                max_length=50, unique=True, verbose_name="Metric Code"
            ),
        ),
        migrations.AlterField(
            model_name="metric",
            name="name",
            field=models.CharField(max_length=50, unique=True, verbose_name="Name"),
        ),
    ]
