# Generated by Django 6.0 on 2025-12-14 04:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stocks", "0002_alter_company_options_alter_metric_code_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="metric",
            name="unit",
        ),
        migrations.RemoveField(
            model_name="timeperiod",
            name="is_complete",
        ),
        migrations.AddField(
            model_name="metric",
            name="formula",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="metric",
            name="is_derived",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="metric",
            name="name",
            field=models.CharField(max_length=50, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="timeperiod",
            name="quarter",
            field=models.SmallIntegerField(
                blank=True, null=True, verbose_name="Quarter"
            ),
        ),
        migrations.CreateModel(
            name="FinancialValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=20,
                        null=True,
                        verbose_name="Value",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="financials",
                        to="stocks.company",
                        verbose_name="Company",
                    ),
                ),
                (
                    "metric",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="values",
                        to="stocks.metric",
                        verbose_name="Metric",
                    ),
                ),
                (
                    "time_period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="values",
                        to="stocks.timeperiod",
                        verbose_name="Time Period",
                    ),
                ),
            ],
            options={
                "verbose_name": "FinancialValue",
                "verbose_name_plural": "FinancialValues",
            },
        ),
    ]
