# Generated by Django 6.0 on 2025-12-14 04:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stocks", "0003_remove_metric_unit_remove_timeperiod_is_complete_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="timeperiod",
            unique_together={("year", "quarter", "period_type")},
        ),
        migrations.AlterField(
            model_name="metric",
            name="category",
            field=models.CharField(
                choices=[
                    ("PnL", "Profit & Loss"),
                    ("QTR", "Quarters"),
                    ("BS", "Balance Sheet"),
                    ("CF", "Cash Flow"),
                    ("RATIO", "Financial Ratios"),
                ],
                max_length=5,
                verbose_name="Category",
            ),
        ),
        migrations.RemoveField(
            model_name="timeperiod",
            name="end_date",
        ),
        migrations.RemoveField(
            model_name="timeperiod",
            name="start_date",
        ),
    ]
