# Generated by Django 6.0 on 2025-12-14 04:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stocks", "0004_alter_timeperiod_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="company",
            options={
                "ordering": ["name"],
                "verbose_name": "Company",
                "verbose_name_plural": "Companies",
            },
        ),
        migrations.AlterModelOptions(
            name="financialvalue",
            options={
                "verbose_name": "Financial Value",
                "verbose_name_plural": "Financial Values",
            },
        ),
        migrations.AlterModelOptions(
            name="metric",
            options={
                "ordering": ["category", "name"],
                "verbose_name": "Metric",
                "verbose_name_plural": "Metrics",
            },
        ),
        migrations.AlterModelOptions(
            name="timeperiod",
            options={
                "ordering": ["-year", "-quarter"],
                "verbose_name": "Time Period",
                "verbose_name_plural": "Time Periods",
            },
        ),
        migrations.AlterField(
            model_name="company",
            name="industry",
            field=models.CharField(max_length=50, verbose_name="Industry"),
        ),
        migrations.AlterField(
            model_name="company",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Active?"),
        ),
        migrations.AlterField(
            model_name="company",
            name="sector",
            field=models.CharField(max_length=50, verbose_name="Sector"),
        ),
        migrations.AlterField(
            model_name="metric",
            name="category",
            field=models.CharField(
                choices=[
                    ("PNL", "Profit & Loss"),
                    ("BS", "Balance Sheet"),
                    ("CF", "Cash Flow"),
                    ("RATIO", "Financial Ratios"),
                ],
                max_length=10,
                verbose_name="Category",
            ),
        ),
        migrations.AlterField(
            model_name="metric",
            name="formula",
            field=models.TextField(blank=True, null=True, verbose_name="Formula"),
        ),
        migrations.AlterField(
            model_name="metric",
            name="is_derived",
            field=models.BooleanField(default=False, verbose_name="Is Derived Metric?"),
        ),
        migrations.AlterField(
            model_name="metric",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Name"),
        ),
        migrations.AlterUniqueTogether(
            name="financialvalue",
            unique_together={("company", "metric", "time_period")},
        ),
        migrations.AddIndex(
            model_name="financialvalue",
            index=models.Index(
                fields=["company", "metric", "time_period"],
                name="stocks_fina_company_81d3a6_idx",
            ),
        ),
    ]
