# Generated by Django 6.0 on 2025-12-14 04:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stocks", "0005_alter_company_options_alter_financialvalue_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="timeperiod",
            name="period_type",
            field=models.CharField(
                choices=[("annual", "Annual"), ("quarterly", "Quarterly")],
                max_length=10,
                verbose_name="Period Type",
            ),
        ),
    ]
