# Generated by Django 6.0 on 2025-12-14 06:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stocks", "0006_alter_timeperiod_period_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="MetricCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        choices=[
                            ("PNL", "Profit & Loss"),
                            ("BS", "Balance Sheet"),
                            ("CF", "Cash Flow"),
                            ("RATIO", "Financial Ratios"),
                        ],
                        max_length=10,
                        unique=True,
                        verbose_name="Category Code",
                    ),
                ),
            ],
            options={
                "verbose_name": "Metric Category",
                "verbose_name_plural": "Metric Categories",
            },
        ),
        migrations.AlterField(
            model_name="metric",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="metrics",
                to="stocks.metriccategory",
                verbose_name="Category",
            ),
        ),
    ]
