# Generated by Django 5.2.9 on 2025-12-19 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0006_remove_company_listing_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Code')),
                ('name', models.CharField(max_length=100, verbose_name='Category')),
            ],
            options={
                'verbose_name': 'IndexCategory',
                'verbose_name_plural': 'IndexCategories',
            },
        ),
        migrations.CreateModel(
            name='Index',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('ticker', models.CharField(max_length=50, verbose_name='Ticker')),
                ('exchange', models.CharField(choices=[('nse', 'NSE'), ('bse', 'BSE')], max_length=50, verbose_name='Exchange')),
                ('calculation_method', models.CharField(max_length=100, verbose_name='Calculation Method')),
                ('rebalancing_frequency', models.CharField(blank=True, max_length=50)),
                ('constituent_count', models.PositiveIntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('base_index', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_indices', to='stocks.index')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stocks.indexcategory', verbose_name='Index Category')),
            ],
            options={
                'verbose_name': 'Index',
                'verbose_name_plural': 'Indices',
            },
        ),
        migrations.CreateModel(
            name='IndexHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('index', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='stocks.index')),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('index', 'date')},
            },
        ),
    ]
